DROP TABLE IF EXISTS USER_DETAILS;

CREATE TABLE USER_DETAILS(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  CITY VARCHAR(50),
  LAT NUMERIC,
  LNG NUMERIC,
  STREET VARCHAR(50),
  SUITE VARCHAR(10),
  ZIPCODE VARCHAR(10),
  BS VARCHAR(100),
  CATCH_PHRASE VARCHAR(500),
  COMPANY_NAME VARCHAR(100),
  EMAIL VARCHAR(100),
  NAME VARCHAR(50),
  PHONE VARCHAR(50),
  USERNAME VARCHAR(20),
  WEBSITE VARCHAR(50)
);
